### ISSUE TITLE
Unable to download Zebra Crossing Dataset

### ISSUE THREAD

**Issue by draxler1** [bubbliiiing/Semantic-Segmentation#9]
I am trying to download zebra crossing dataset via provided Baidu platform. That link seems to be currepted.
Can you provide direct Google Drive link or any other well known platform than Biadu....

Or can you provide weights for Segnet_Mobile Model??

**Comment by bubbliiiing** [comment]
I can't connect to Google drive, Do you want to test the zebra crossing or just to learn the model.

**Comment by bubbliiiing** [comment]
If you want to detect the zebra crossing, leave your email and I'll send it to you

**Comment by draxler1** [comment]
Thank you for your quick reply.
Dataset and weights would be helpful :)

Email : 
nitngp@gmail.com
